// Select color input
let chosenColor = $('#colorPicker').val();
$('#colorPicker').change(function() {
  chosenColor = $('#colorPicker').val();
});

// Select size input
$('#sizePicker').submit(function(e) {
  e.preventDefault();
  makeGrid();
});

// When size is submitted by the user, call makeGrid()
function makeGrid() {
  let squareCount = 0;
  let height = $('#input_height').val();
  let width = $('#input_width').val();

  $('#input_height').attr('value', height);
  $('#input_width').attr('value', width);

  //The canvas is erased and regenerated with each form submit.
  $('#pixel_canvas').children().remove();

  //The grid is generated by rows, then squares in each row.
  //Each square is given an on-click event listener upon creation.
  for(var m=0; m<height; m++) {
    $('#pixel_canvas').append("<tr class='row_"+m+"'></tr>");
    $('.row_'+m).css('height', '30px');
    $('.row_'+m).css('border', '2px solid black');

    for(var n=0; n<width; n++) {
      $('.row_'+m).append("<td class='square_"+squareCount+"'></tr>");
      $('.square_'+squareCount).css('width', '30px');
      $('.square_'+squareCount).css('border', '2px solid black');
      $('.square_'+squareCount).click(function() {
        $(this).css('background-color', chosenColor);
      });
      squareCount++;
    }
  }
}
